title: All in one
dev: true
splash:
  message: This is the all in one combo.
  after_validate: script/select_stage_group
  fields:
    - name: before_start
      type: basic.shorttext
      optional: true
      source: before_start_text
stage_groups:
  - name: first
    stages:
      - basic_1
      - basic_2
      - selects_1
stages:
  basic_1:
    fields:
      - name: Basic text
        type: basic.shorttext
        optional: false
      - name: Basic Longtext
        type: basic.longtext
        optional: false
      - name: Basic Range
        type: basic.range
        optional: false
      - name: Basic Select
        type: basic.select
        optional: false
        source: select_options1
      - name: Basic Multi Selct
        type: basic.multiselect
        optional: false
        source: select_options2
  basic_2:
    field:
      - name: Basic Phone
        type: basic.phone
        optional: false
      - name: Basic Checkbox
        type: basic.checkbox
        optional: false
      - name: Basic Color
        type: basic.color
        optional: false
      - name: Basic Date
        type: basic.date
        optional: false
      - name: Basic Date Time
        type: basic.datetime
        optional: false
      - name: Basic Email
        type: basic.email
        optional: false
      - name: Basic number
        type: basic.shorttext
        optional: false
      - name: Basic Paragraph
        type: basic.shorttext
        optional: false
  selects_1:
    fields:
      - name: Select Month
        type: select.month
        optional: false
      - name: Select Week
        type: select.week
        optional: false
      - name: Select Nested
        type: select.nested
        optional: false

sources:
  before_start_text:
    type: static
    data: This mobo jumbo before starting the flow.
  source1:
    type: static
    data: [1, 2, 3]
  select_options1:
    type: static
    data:
      - one
      - two
      - three
      - four
      - five
  select_options2:
    type: static
    data:
      - apple
      - banana
      - pineapple
      - mango
      - orange
  nested_select_data:
    type: static
    data:
      nested_order: ["bing", "bang", "bong"]
      options:
        - name: abc
          options:
            - name: abc1
              options:
                - name: mango
                - name: apple
            - name: abc2
              options:
                - name: pineapple
                - name: peanuts
            - name: abc3
              options:
                - name: almond
                - name: peas
            - name: abc4
              options:
                - name: mango
                - name: apple
        - name: pqr
          options:
            - name: pqr1
              options:
                - name: mango
                - name: orange
            - name: pqr2
              options:
                - name: mango
                - name: banana
